version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jna-business-solutions
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - jna-network
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./data/nginx:/var/cache/nginx

networks:
  jna-network:
    driver: bridge
